development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: craft_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("CRAFT_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("CRAFT_PASSWORD") { 'root' } %>
  host: <%= ENV.fetch("CRAFT_DATABASE_HOST") { 'mysql' } %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: craft_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("CRAFT_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("CRAFT_PASSWORD") { 'root' } %>
  host: <%= ENV.fetch("CRAFT_DATABASE_HOST") { 'mysql' } %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: craft_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("CRAFT_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("CRAFT_PASSWORD") { 'root' } %>
  host: <%= ENV.fetch("CRAFT_DATABASE_HOST") { 'mysql' } %>
