development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: craft_development
  pool: 5
  username: root
  password: root
  host: mysql

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: craft_test
  pool: 5
  username: root
  password: root
  host: mysql

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: craft_production
  pool: 5
  username: root
  password: root
  host: mysql
