version: "3"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:6.2.4
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    command: "redis-server"

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/craft/backend
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - mysql
      - redis
    environment:
      REDIS_URL : redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/craft/frontend
    ports:
      - "3001:3000"
    command: sh -c "yarn start"
    tty: true
    stdin_open: true
    depends_on:
      - mysql
      - redis
