source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'active_model_serializers'
gem 'aws-sdk-s3'
gem 'bootsnap', require: false
gem 'carrierwave'
gem 'firebase-auth-rails'
gem 'fog-aws'
gem 'kaminari'
gem 'mysql2'
gem 'puma'
gem 'rack-cors'
gem 'rails', '~> 6.1'
gem 'ransack'
gem 'sprockets', '~> 3.7.2'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'webpacker'
gem 'whenever', require: false

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'rspec-rails', '~> 5.0.0'
end

group :development do
  gem 'capistrano', require: false
  gem 'capistrano3-unicorn'
  gem 'capistrano-bundler'
  gem 'capistrano-rails', require: false
  gem 'capistrano-rbenv'
  gem 'listen', '~> 3.2'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :production do
  gem 'unicorn'
end
