version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    working_directory: ~/craft
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - run:
          name: dependency_setup
          command: gem install bundler
          working_directory: backend
      - run:
          name: dependency_setup
          command: bundle install
          working_directory: backend
      - run:
          name: dependency_setup
          command: bundle exec rspec
          working_directory: backend
workflows:
  test: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - build

