version: 2.1
orbs:
  cypress: cypress-io/cypress@1.28.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          RAILS_ENV: test
          CRAFT_DATABASE_HOST: 127.0.0.1
          CRAFT_USERNAME: 'root'
          CRAFT_PASSWORD: ""

      - image: circleci/mysql:8.0
        command: --default-authentication-plugin=mysql_native_password

    working_directory: ~/craft/backend

    steps:
      - checkout:
          path: ~/craft
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Gemfile.lock" }}
          - v2-dependencies-
      - run:
          name: prepare bundler
          command: gem install bundler -v 2.2.28
      - run:
          name: install dependencies
          command: bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run:
          name: rubocop
          command: bundle exec rubocop

      - run:
          name: rspec
          command: bundle exec rspec

  react_start:
    docker:
      - image: circleci/node:15.14.0

    working_directory: ~/craft/frontend

    steps:
      - checkout:
          path: ~/craft
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          - v2-dependencies-
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: yarn start
          command: yarn start
          background: true

workflows:
  build:
    jobs:
      - build
      - react_start:
          requires:
            - build
      - cypress/run:
          yarn: true
          working_directory: ~/craft/frontend/e2e




