development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: craft_development
  pool: 5
  username: root
  password: Syuu0210
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: craft_test
  pool: 5
  username: root
  password: Syuu0210
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: craft_production
  pool: 5
  username: root
  password: Syuu0210
  host: localhost
